### ISSUE TITLE
Implement material UI for the whole page 

### ISSUE THREAD

**Issue by adiXcodr** [thebishaldeb/IEEE_TU#4]
Design the UI of the web page with the colour scheme of your choice. Please leave a comment if you are interested

**Comment by adiXcodr** [comment]
I will be working on this, more participants and ideas are welcomed though

**Comment by thebishaldeb** [comment]
> I will be working on this, more participants and ideas are welcomed though

I want you'll to decide the color scheme together so that different parts don't get differently colored and look weird.
